### ISSUE TITLE
Wrong GitHub urls using oss-find-source tool 

### ISSUE THREAD

**Issue by simonepirocca** [microsoft/OSSGadget#153]
I'm conducting a research about pypi packages, in which I had first of all to gather the GitHub url of 4000 different packages. To do that I used at first a home-made web crawler and then the oss-find-source tool to double-check them. During this phase I found that for 8 packages the url given by your tool was wrong. I hope this issue will help you improving the source code. Here is the exact list, that follows the structure "package_name: oss-find-source_wrong_url --> right_github_url".

- ninja: https://github.com/scikit-build/ninja-python-distributions --> https://github.com/ninja-build/ninja
- imagecodecs: https://github.com/uclouvain/openjpeg --> https://github.com/scossu/imagecodecs
- simpy: https://github.com/r-simmer/simmer --> https://github.com/simpx/simpy
- plotly: https://github.com/plotly/orca --> https://github.com/plotly/plotly.py 
- statistics: https://github.com/python/cpython --> https://github.com/digitalemagine/py-statistics
- sphinx-autobuild: https://github.com/garetjax/sphinx_autobuild --> https://github.com/garetjax/sphinx-autobuild
- pydruid: https://github.com/metamx/pydruid --> https://github.com/druid-io/pydruid
- repoze-who: https://github.com/repoze/repoze --> https://github.com/repoze/repoze.who

**Comment by scovetta** [comment]
Thanks for the report, @simonepirocca, and for taking the time to test the tool.

For ninja, this is a bug. We should be looking at `download_url` and `project_urls` closer, and prioritize any GitHub URLs we find there over a full text search, which is where we found `scikit-build/ninja-python-distributions`.

For imagecodecs, I couldn't find any reference to `scossu/imagecodecs` from the [PyPI JSON page](https://pypi.org/pypi/imagecodecs/json). Where did you find the correct GitHub URL for this?

For simpy, same as imagecodecs.

For plotly, same bug as for ninja.

For statistics, this is a different bug. The only reference to the right GitHub URL is found in the description (free text), but we see `python/cpython` as well in that text, and don't have a way to prefer one over the other (by default, we should show both in the output). We could improve this by comparing the edit distance between the package name ("statistics") and the GitHub owner/repo, which should be closer for py-statistics than for cpython. So definitely a place we can improve.

For sphinx-autobuild, the PyPI metadata has sphinx_autobuild in some places and sphinx-autobuild in others, and right now, I think we only [look](https://github.com/microsoft/OSSGadget/blob/main/src/Shared/PackageManagers/PyPIProjectManager.cs#L162) in `info.homepage` and `info.home_page`, and fall back to a full text search. We should extend this to include other fields like package_url, project_url, project_urls.*, etc.

For pydruid, same as sphinx-autobuild. The better GitHub URL is hiding in `project_urls.Bug Tracker` and `project_urls.Source Code`.

For repoze-who, this is due to a missing character in the regex that we use to extract GitHub URLs [here](https://github.com/microsoft/OSSGadget/blob/main/src/Shared/PackageManagers/GitHubProjectManager.cs#L183).

So we should be able to fix an update out soon with these fixes, and thank you again for taking the time to report these!

**Comment by scovetta** [comment]
Fixed via #156
