### ISSUE TITLE
OSS Gadget Releases aren't being published as single files.

### ISSUE THREAD

**Issue by gfs** [microsoft/OSSGadget#217]
Lots of files in the linux release.

**Comment by gfs** [comment]
https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file

-p:PublishSingleFile=true --self-contained true

**Comment by daalcant** [comment]
Current plan is to remove the Shared library from the release bundle and convert the tools to Single-File. Will be resolved after or alongside #213.

**Comment by daalcant** [comment]
Publishing using the PublishSingleFile property is increasing the total unpacked size of a release by 4.5-5x (from ~100 MB to ~500 MB). I believe this is because the .NET runtime is again being bundled with each project built by the solution. Reconsideration would likely require a revised project structure or build/release strategy.

**Comment by gfs** [comment]
Makes sense that single file would do that.  Overlooked that when I added that.

**Comment by gfs** [comment]
Won't fix.
