### ISSUE TITLE
Specify `self-contained` for .NET 6.

### ISSUE THREAD

**Issue by scovetta** [microsoft/OSSGadget#340]
.NET 6 introduced a change that requires `self-contained` to be explicitly specified if `runtimeIdentifiers` are too.

Details at: https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/runtimeidentifier-self-contained

We might need to include `<SelfContained>false</SelfContained>` in each of the tool .csproj files, or change the arguments in the `Pipelines/templates/dotenet-build-publish-all-platforms-job.yml` file.

**Comment by gfs** [comment]
Is there something currently not working? 

--sc is specified in the pipeline 

it's not documented on docs.Microsoft.com for the publish command but that should be the same as --self-contained true. 

https://github.com/microsoft/OSSGadget/blob/b8e776d972630ed1ffa7286781014e58afdff0bd/Pipelines/templates/dotnet-build-publish-all-platforms-job.yml#L106

See this issue for sort of documentation on --sc

https://github.com/dotnet/sdk/issues/21405

**Comment by gfs** [comment]
https://github.com/dotnet/docs/issues/30025

**Comment by gfs** [comment]
> Filed an issue to update docs.Microsoft.com.  
> 
> https://github.com/dotnet/docs/issues/30025

Docs have been updated to document the `--sc` flag.

**Comment by scovetta** [comment]
This is the warning I'm seeing in the build logs:

![image](https://user-images.githubusercontent.com/732166/176289615-42d76156-b8eb-4bdd-838e-7bf04e85c0ff.png)

**Comment by gfs** [comment]
> This is the warning I'm seeing in the build logs:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/732166/176289615-42d76156-b8eb-4bdd-838e-7bf04e85c0ff.png)
> 
> 

Got it I might have missed one of the publish commands. Will make a scrub of the pipeline.

**Comment by gfs** [comment]
It looks like this is caused by the "build" commands which happen before "publish". These build commands also have a rid. 

I don't know why there are build commands at all. Do you know why the pipeline does this? Per dotnet documentation and my experience you only need to (and only should) publish for distribution. "Build" doesn't produce assets that are expected to be distributed. 

This is the first of the 3 build commands. After the 3 builds there are 4 publishes. 

https://github.com/microsoft/OSSGadget/blob/b8e776d972630ed1ffa7286781014e58afdff0bd/Pipelines/templates/dotnet-build-publish-all-platforms-job.yml#L70

From dotnet documentation:

> The dotnet publish command's output is ready for deployment to a hosting system (for example, a server, PC, Mac, laptop) for execution. It's the only officially supported way to prepare the application for deployment.

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish
