### ISSUE TITLE
Wrong parameter order in OssGadgetLib.cs?

### ISSUE THREAD

**Issue by gaokai320** [microsoft/OSSGadget#397]
I am reading the source code of `oss-find-source`. Although I am not familiar with C#, after checking the API reference of [`Check.NotNull`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.rest.clientruntime.azure.authentication.utilities.check.notnull?view=azure-dotnet), I think this line of code may have wrong order of `nameof(projectManagerFactory)` and `projectManagerFactory`?
https://github.com/microsoft/OSSGadget/blob/ebd2e46ccf880491910dec33530dfe067df9e0cb/src/Shared/OssGadgetLib.cs#L35

**Comment by gfs** [comment]
I suspect this is already closed because you discovered this on your own. Just for documentation purposes, the reason this isn't an issue is because this call to `Check.NotNull` is implemented in OssGadget itself with a different parameter pattern than the azure one linked above: https://github.com/microsoft/OSSGadget/blob/4c84c9100eb0684ab7a7484d1755bc86a70ad008/src/Shared/Helpers/Check.cs#L46
